// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcnpyfzzsbohtrqbkroo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjbnB5Znp6c2JvaHRycWJrcm9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNDIzNTIsImV4cCI6MjA1ODkxODM1Mn0.xtgHkgCfeZQJ4UmGmkzkkCNPDY-Gn3VXmOYvYnIbPVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);